#

In [3]:
x <- c(5)
x

[1] 5

In [4]:
matrix(1:6, nrow=2, ncol=3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [5]:
matrix(1:6, nrow=2, ncol=3,byrow=T)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [7]:
r1 <- c(1:3)
r2 <- c(4:6)
rbind(r1,r2)

[,1] [,2] [,3]
r1 1    2    3   
r2 4    5    6

In [8]:
c1 <- c(1,4)
c2 <- c(2,5)
c3 <- c(3,6)
cbind(c1,c2,c3)

c1 c2 c3
[1,] 1  2  3 
[2,] 4  5  6

In [10]:
x <- matrix(1:6, nrow=2, ncol=3)
print(x[1,2])
print(x[1,])
print(x[,3])

[1] 3
[1] 1 3 5
[1] 5 6
